name: 'Npm Publish'
description: 'Publish a package to the NPM registry'
author: '欧阳鑫'
inputs:
  
  workspaces:
    description: 'Publish these workspace packages to the NPM registry, you can use "," split'
    # eg: build/common,build/shared,build/core ...
    default: '.'
  
  releaseType:
    description: 'You can specify the type of release, support 'major' | 'premajor' | 'minor' | 'preminor' | 'patch' | 'prepatch' | 'prerelease''
    default: 'patch'

  registry:
    description: 'Specify the publish registry'
    default: 'https://registry.npmjs.org'
  
  tag:next:
    description: '[Optional] publish tag with next'
runs:
  using: 'node12'
  main: 'dist/index.js'
